// Development environment configuration
// This file is used for local development
// In production, this file is generated by entrypoint.sh
window.env = {
  API_URL: "http://localhost:3002",
  GAME_URL: "http://localhost:8080"
};
